-- MySQL Script generated by MySQL Workbench
-- Fri Jul 28 07:23:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema solardb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `device` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `port` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `port_UNIQUE` (`port` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
COMMENT = 'device table';


-- -----------------------------------------------------
-- Table `field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `field` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(100) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `category` VARCHAR(10) NOT NULL DEFAULT 'simple',
  `format` VARCHAR(1) NOT NULL DEFAULT 'N',
  `registeraddr` VARCHAR(13) NOT NULL,
  `to_dashboard` TINYINT(4) NOT NULL DEFAULT 0 COMMENT 'if 1 then must be persisted to dashboard table',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `registeraddr_UNIQUE` (`registeraddr` ASC) VISIBLE,
  UNIQUE INDEX `label_UNIQUE` (`label` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12;


-- -----------------------------------------------------
-- Table `dashboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dashboard` (
  `id` INT(11) NOT NULL,
  `identifier` VARCHAR(24) NOT NULL,
  `field_id` INT(11) NULL DEFAULT NULL,
  `device_id` INT(11) NULL DEFAULT NULL,
  `value` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dashboard_field1_idx` (`field_id` ASC) VISIBLE,
  INDEX `fk_dashboard_device1_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `fk_dashboard_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dashboard_field1`
    FOREIGN KEY (`field_id`)
    REFERENCES `field` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `device_id` INT(11) NOT NULL,
  `field_id` INT(11) NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `value` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_data_device_idx` (`device_id` ASC) VISIBLE,
  INDEX `fk_data_field1_idx` (`field_id` ASC) VISIBLE,
  INDEX `data_date_idx` USING BTREE (`date`) VISIBLE,
  CONSTRAINT `fk_data_device`
    FOREIGN KEY (`device_id`)
    REFERENCES `device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_field1`
    FOREIGN KEY (`field_id`)
    REFERENCES `field` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1053408;


-- -----------------------------------------------------
-- Placeholder table for view `dashboard_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dashboard_view` (`identifier` INT, `value` INT);

-- -----------------------------------------------------
-- Placeholder table for view `today_kwh_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `today_kwh_view` (`id` INT);

-- -----------------------------------------------------
-- View `dashboard_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dashboard_view`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`solardb`@`%` SQL SECURITY DEFINER VIEW `dashboard_view` AS select `d`.`identifier` AS `identifier`,case when `d`.`identifier` = 'load' then truncate(sum(`d`.`value`),2) when `d`.`identifier` in ('batt_voltage','batt_soc') then truncate(avg(`d`.`value`),2) end AS `value` from `dashboard` `d` where `d`.`value` > 0 group by `d`.`identifier`;

-- -----------------------------------------------------
-- View `today_kwh_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `today_kwh_view`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`solardb`@`%` SQL SECURITY DEFINER VIEW `solardb`.`today_kwh_view` AS with average as (select `d`.`name` AS `name`,min(`z`.`date`) AS `start`,max(`z`.`date`) AS `end`,truncate(avg(`z`.`value`) * timestampdiff(SECOND,min(`z`.`date`),max(`z`.`date`)) / 3600 / 1000,2) AS `kwh`,truncate(avg(`z`.`value`),2) AS `moy` from ((`solardb`.`data` `z` join `solardb`.`device` `d` on(`d`.`id` = `z`.`device_id`)) join `solardb`.`field` `f` on(`f`.`id` = `z`.`field_id`)) where 1 = 1 and `f`.`name` = 'rated_watt' and date_format(`z`.`date`,'%Y-%m-%d') = curdate() group by `d`.`name`)select date_format(`average`.`start`,'%d/%m/%Y') AS `date`,date_format(`average`.`start`,'%h:%i:%S') AS `startedAt`,date_format(`average`.`end`,'%h:%i:%S') AS `endedAt`,concat(sum(`average`.`kwh`),' kWh') AS `kWh`,concat(`average`.`moy`,' W') AS `averageWatts` from `average`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
