{
 "title": "solardb-sqlite",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Sortie 12v",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select\n\tCAST(((SUM(value) / SUM(CASE WHEN value > 0 THEN 1 ELSE 0 END)) * 100) as int) / 100.0 AS value\nfrom\n\tdashboard d\nwhere\n\td.identifier = 'load'",
     "rawQueryText": "select\n\tCAST(((SUM(value) / SUM(CASE WHEN value > 0 THEN 1 ELSE 0 END)) * 100) as int) / 100.0 AS value\nfrom\n\tdashboard d\nwhere\n\td.identifier = 'load'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Voltage batterie",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select\n\tcast(((SUM(value) / SUM(CASE WHEN value > 0 THEN 1 ELSE 0 END)) * 100) as int) / 100.0 AS value\nfrom\n\tdashboard d\nwhere\n\td.identifier = 'batt_voltage'",
     "rawQueryText": "select\n\tcast(((SUM(value) / SUM(CASE WHEN value > 0 THEN 1 ELSE 0 END)) * 100) as int) / 100.0 AS value\nfrom\n\tdashboard d\nwhere\n\td.identifier = 'batt_voltage'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Entrée solaire",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH mysel (device,\nvalue) AS (\nSELECT\n\tdevice.name,\n\tdata.value\nFROM\n\tdata\nJOIN device ON\n\tdevice.id = data.device_id\nWHERE\n\tdata.field_id = 7\nORDER BY\n\tdata.id DESC\nLIMIT 3\n)\nSELECT\n\tSUM(mysel.value) AS watts\nFROM\n\tmysel;",
     "rawQueryText": "WITH mysel (device,\nvalue) AS (\nSELECT\n\tdevice.name,\n\tdata.value\nFROM\n\tdata\nJOIN device ON\n\tdevice.id = data.device_id\nWHERE\n\tdata.field_id = 7\nORDER BY\n\tdata.id DESC\nLIMIT 3\n)\nSELECT\n\tSUM(mysel.value) AS watts\nFROM\n\tmysel;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "RDC 230v",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select value from dashboard where identifier = 'hv_active_power'",
     "rawQueryText": "select value from dashboard where identifier = 'hv_active_power'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "ETG 230v",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select value from dashboard where identifier = 'hv_active_power_etg1'",
     "rawQueryText": "select value from dashboard where identifier = 'hv_active_power_etg1'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Production dernier jour",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n(24 * (julianday(d.ended_at) - JULIANDAY(d.started_at))) * sum(dd.avgval) AS production \nfrom diary_data dd \njoin diary d ON d.id = dd.diary_id \njoin field f ON f.id = dd.field_id \nwhere f.name = 'pv_rated_watt'\nand d.id = (select max(id) from diary)\n",
     "rawQueryText": "SELECT \n(24 * (julianday(d.ended_at) - JULIANDAY(d.started_at))) * sum(dd.avgval) AS production \nfrom diary_data dd \njoin diary d ON d.id = dd.diary_id \njoin field f ON f.id = dd.field_id \nwhere f.name = 'pv_rated_watt'\nand d.id = (select max(id) from diary)\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Heure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select strftime('%H:%M:%S', DATETIME('now', 'localtime')) as value;",
     "rawQueryText": "select strftime('%H:%M:%S', DATETIME('now', 'localtime')) as value;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Production du mois",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH dataset AS (\n  SELECT\n    (24 * (julianday(d.ended_at) - JULIANDAY(d.started_at))) * dd.avgval AS production\n  FROM diary_data dd\n  JOIN diary d ON d.id = dd.diary_id\n  JOIN field f ON f.id = dd.field_id\n  WHERE f.name = 'pv_rated_watt'   \n)\nSELECT sum(production) FROM dataset\n",
     "rawQueryText": "WITH dataset AS (\n  SELECT\n    (24 * (julianday(d.ended_at) - JULIANDAY(d.started_at))) * dd.avgval AS production\n  FROM diary_data dd\n  JOIN diary d ON d.id = dd.diary_id\n  JOIN field f ON f.id = dd.field_id\n  WHERE f.name = 'pv_rated_watt'   \n)\nSELECT sum(production) FROM dataset\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select\n\tCAST(((SUM(value) / SUM(CASE WHEN value > 0 THEN 1 ELSE 0 END)) * 100) as int) / 100.0 AS value\nfrom\n\tdashboard d\nwhere\n\td.identifier = 'temperature'",
     "rawQueryText": "select\n\tCAST(((SUM(value) / SUM(CASE WHEN value > 0 THEN 1 ELSE 0 END)) * 100) as int) / 100.0 AS value\nfrom\n\tdashboard d\nwhere\n\td.identifier = 'temperature'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "% batterie",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select\n\tCAST(((SUM(value) / SUM(CASE WHEN value > 0 THEN 1 ELSE 0 END)) * 100) as int) / 100.0 AS value\nfrom\n\tdashboard d\nwhere\n\td.identifier = 'batt_soc'",
     "rawQueryText": "select\n\tCAST(((SUM(value) / SUM(CASE WHEN value > 0 THEN 1 ELSE 0 END)) * 100) as int) / 100.0 AS value\nfrom\n\tdashboard d\nwhere\n\td.identifier = 'batt_soc'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Production",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "queryText": "SELECT\n\tunixepoch(DATETIME(z.`date`, '-1 hour')) AS `time`,\n\td.name,\n\tz.value\nFROM\n\tdata AS z\nJOIN device d ON\n\td.id = z.device_id\nJOIN field f ON\n\tf.id = z.field_id\nWHERE\n\tDATE(z.`date`) = DATE('now')\n\tAND f.name = 'rated_watt'\norder by\n\tz.`date` DESC\n",
     "rawQueryText": "SELECT\n\tunixepoch(DATETIME(z.`date`, '-1 hour')) AS `time`,\n\td.name,\n\tz.value\nFROM\n\tdata AS z\nJOIN device d ON\n\td.id = z.device_id\nJOIN field f ON\n\tf.id = z.field_id\nWHERE\n\tDATE(z.`date`) = DATE('now')\n\tAND f.name = 'rated_watt'\norder by\n\tz.`date` DESC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Statistiques dernier jour",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "queryText": "SELECT \ndv.name AS device, \ndd.maxval AS Highest, \ndd.avgval As Average,\n(24 * (julianday(d.ended_at) - JULIANDAY(d.started_at))) * dd.avgval AS production \nfrom diary_data dd \njoin diary d ON d.id = dd.diary_id \njoin field f ON f.id = dd.field_id \njoin device dv ON dv.id  = dd.device_id\nwhere f.name = 'pv_rated_watt'\nand d.id = (select max(id) from diary)\nORDER BY dv.name DESC\n",
     "rawQueryText": "SELECT \ndv.name AS device, \ndd.maxval AS Highest, \ndd.avgval As Average,\n(24 * (julianday(d.ended_at) - JULIANDAY(d.started_at))) * dd.avgval AS production \nfrom diary_data dd \njoin diary d ON d.id = dd.diary_id \njoin field f ON f.id = dd.field_id \njoin device dv ON dv.id  = dd.device_id\nwhere f.name = 'pv_rated_watt'\nand d.id = (select max(id) from diary)\nORDER BY dv.name DESC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Statistiques",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "queryText": "SELECT \ndv.name AS device, \nmax(dd.maxval) AS Highest, \nmax(dd.avgval) As Average,\n(24 * (julianday(d.ended_at) - JULIANDAY(d.started_at))) * sum(dd.avgval) AS production \nfrom diary_data dd \njoin diary d ON d.id = dd.diary_id \njoin field f ON f.id = dd.field_id \njoin device dv ON dv.id  = dd.device_id\nwhere f.name = 'pv_rated_watt'\nGROUP BY dv.name\nORDER BY d.id, dv.name DESC\n",
     "rawQueryText": "SELECT \ndv.name AS device, \nmax(dd.maxval) AS Highest, \nmax(dd.avgval) As Average,\n(24 * (julianday(d.ended_at) - JULIANDAY(d.started_at))) * sum(dd.avgval) AS production \nfrom diary_data dd \njoin diary d ON d.id = dd.diary_id \njoin field f ON f.id = dd.field_id \njoin device dv ON dv.id  = dd.device_id\nwhere f.name = 'pv_rated_watt'\nGROUP BY dv.name\nORDER BY d.id, dv.name DESC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Ensoleillement",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 13 },
   "targets": [
    {
     "queryText": "select \n  strftime('%d/%m/%Y', d.datestamp) As Jour, \n  d.started_at As Début, \n  d.ended_at As Fin,\n  (\n    SELECT\n    (24 * (julianday(d.ended_at) - JULIANDAY(d.started_at))) * SUM(diary_data.avgval)\n    FROM diary_data\n    JOIN field f ON f.id = diary_data.field_id\n    WHERE diary_data.diary_id = d.id\n    AND f.name = 'pv_rated_watt'\n  ) AS Production\n  from diary d\n  order by d.id desc\n  ;",
     "rawQueryText": "select \n  strftime('%d/%m/%Y', d.datestamp) As Jour, \n  d.started_at As Début, \n  d.ended_at As Fin,\n  (\n    SELECT\n    (24 * (julianday(d.ended_at) - JULIANDAY(d.started_at))) * SUM(diary_data.avgval)\n    FROM diary_data\n    JOIN field f ON f.id = diary_data.field_id\n    WHERE diary_data.diary_id = d.id\n    AND f.name = 'pv_rated_watt'\n  ) AS Production\n  from diary d\n  order by d.id desc\n  ;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}